theme: jekyll-theme-cayman
github: [metadata]
exclude: ['README.md', 'CNAME', 'Gemfile.lock', 'Gemfile', 'moneycoachwebsite.sublime-project', 'moneycoachwebsite.sublime-workspace', 'testposts']

title: Bountiful Money, LLC
name: Bountiful Money, LLC
description: "Save money, budget according to your values, and experience financial bliss"
author: Cecilia Case
email: cecilia@bountifulmoneyllc.com
url: http://www.bountifulmoneycoach.com

excerpt_separator: <!--more-->
#permalink: /:title/

show_downloads: false
google_analytics: [UA-68706789-4]

# Don't show posts written in the future
future: false

# Front matter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "Cecilia Case"
      email: cecilia@bountifulmoneyllc.com

collections:
  - reviews

plugins:
  - jekyll-feed

## TODO:
## Add suggested posts to end of post
